### ISSUE TITLE
Dropbox Error (429)

### ISSUE THREAD

**Issue by YoshuaSamuelson** [amshove/GC_little_helper#117]
Hello,
I'm unable to do sync with Dropbox. Every time since using GC_little_helper I'm unable to sync.

Its a little annoying for me, because on every click on GC.com web page I got a Dropbox login window.

Yes, I'm using Dropbox, I filled the login and every time I get the Error 429.

How to disable the Dropbox sync? I dont see anywhere this option.

Thanks.

**Comment by lukeIam** [comment]
429 is `Too Many Requests`

> How to disable the Dropbox sync?

Just disable `Auto apply DB-config` if you set it. (it should be opt-in)

**Comment by Anjilajack** [comment]
![dropbox-toll-free](https://cloud.githubusercontent.com/assets/18631288/15015564/4a71381a-122a-11e6-99c7-ff61087a3eea.jpg)


Dropbox error 429 fix help line number +1888 8829 624 with our 247 active technical support team.What you all have to do is to reach our support team cost free in case of any trouble related to files and folders synchronization with drop box,drop box crash and various other problems pertaining to dropbox. We assure you to fix up the problem as soon as possible.After all the problem is not only yours,Its ours.At just a drop of a hat our technical experts will look into deep either for dropbox for home or dropbox for business.Trust us your data is in the safe pair of hands as it gets stored easily on cloud server of dropbox with auto-synchronization option to your PC,Phone tablet from any corner of the planet.So now wherever you go your data accompanies you.All your data is not all vulnerable to any risk of theft,damage,misuse or hacked as it is as safe as banks.You can store any file or folder as long as u wish to.
Recalling you once again we wish to serve you best without being at rest.Buzz us 247 any issue,any complain on our toll free number..
![dropbox-toll-free](https://cloud.githubusercontent.com/assets/18631288/15015545/2fece480-122a-11e6-9dbb-d38b00c0e9fc.jpg)
